openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /timetable/schools/:
    get:
      operationId: listSchools
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/School'
          description: ''
      tags:
      - timetable
  /timetable/available/:
    get:
      operationId: listOnlines
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - timetable
  /version/:
    get:
      operationId: listVersions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Version'
          description: ''
      tags:
      - version
    post:
      operationId: createVersion
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Version'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Version'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Version'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
          description: ''
      tags:
      - version
  /timetable/get-class/:
    post:
      operationId: createSearchClass
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/search-group/:
    post:
      operationId: createSearchGroups
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/upload:
    post:
      operationId: createTimetableLoad
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/lessons/:
    post:
      operationId: createLessonsList
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/teachers/:
    post:
      operationId: createTeachersList
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/lessons/teachers/:
    post:
      operationId: createLessonsListTeachers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/subjects/foreign-languages/:
    post:
      operationId: createForeignLanguageSubjects
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/subjects/profile/:
    post:
      operationId: createProfileSubjectsList
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/groups/profile/:
    post:
      operationId: createProfileGroupsList
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/subjects/mesk/:
    post:
      operationId: createMeskPreparationSubjects
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/classrooms/empty/:
    post:
      operationId: createEmptyClassroom
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /timetable/classroom/lessons/:
    post:
      operationId: createClassroomLessons
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - timetable
  /telegram/notify-admins/:
    post:
      operationId: createNotifyAdmins
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - telegram
components:
  schemas:
    School:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        city:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              maxLength: 50
          required:
          - name
          readOnly: true
      required:
      - name
    Version:
      type: object
      properties:
        major:
          type: integer
          maximum: 32767
          minimum: 0
        minor:
          type: integer
          maximum: 32767
          minimum: 0
        patch:
          type: integer
          maximum: 32767
          minimum: 0
      required:
      - major
      - minor
      - patch
